#! /bin/sh

#########AUTOSTART###############
sxhkd &
$HOME/.config/polybar/launch.sh &
xrdb .Xresources &
nitrogen --restore &
picom --config ~/.config/picom/picom.conf  &
xsetroot -cursor_name left_ptr &
dunst &
##################################

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          0
bspc config window_gap            10
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a zoom state=floating desktop='^3'
bspc rule -a discord desktop='^10'
bspc rule -a SoundWireServer desktop='^9' state=floating
bspc rule -a VSCodium desktop='^1'
bspc rule -a emacs state=tiling

